name: AWS EC2 Backend Deploy


# 워크 플로우가 언제 실행 될지를 정한다.
on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - main
    paths:
      - back-end/**
  pull_request:
    branches:
      - develop
      - main
    paths:
      - back-end/**



permissions:
  contents: read


jobs:
  build:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./back-end
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Copy application-prod.yml
        run: echo "${{ secrets.APPLICATION_PROD_YML }}" > src/main/resources/application-prod.yml

      - name: Build with Gradle
        run: ./gradlew build

      - name: Rename JAR file
        run: mv build/libs/*SNAPSHOT.jar app.jar

      - name: Deploy to EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEYPAIR }}" > private_key.pem
          chmod 600 private_key.pem
          scp -i private_key.pem -o StrictHostKeyChecking=no app.jar ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USERNAME }}/app.jar
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "/home/${{ secrets.EC2_USERNAME }}/restart-server.sh &"
          rm -f private_key.pem